### ISSUE TITLE
Since migrating to Python 3.8, plugin fails to load due to debugtools using Python 3.3

### ISSUE THREAD

**Issue by rahul-ramadas** [evandrocoan/SublimeQuickSettings#2]
When trying to load the QuickSettings plugin, I see the following in the Sublime console:

```
Package Control: The dependency 'debugtools' is not currently installed; installing...
reloading python 3.3 plugin debugtools.setup
Package Control: The dependency 'debugtools' has successfully been installed or updated
Package Control: The dependency 'channelmanager' is not currently installed; installing...
Package Control: The dependency 'channelmanager' has successfully been installed or updated
reloading settings Packages/User/Package Control.sublime-settings
ignored packages updated to: ["PlantUmlDiagrams", "Vintage"]
reloading settings Packages/QuickSettings/Preferences.sublime-settings
reloading settings Packages/User/Package Control.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
reloading plugin QuickSettings.quick_settings
Traceback (most recent call last):
  File "E:\Sublime\Lib\python38\sublime_plugin.py", line 312, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 808, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Sublime\Data\Installed Packages\QuickSettings.sublime-package\quick_settings.py", line 19, in <module>
ModuleNotFoundError: No module named 'debug_tools'
```
That seems to imply that QuickSettings is using Python 3.8, as per the new `.python-version` file added, but `debugtools` is still using Python 3.3? Is this some kind of torn state in my environment?

**Comment by evandrocoan** [comment]
The official Package Control does not yet support Python 3.8. I already added support for Python 3.8 to my fork: https://github.com/evandrocoan/PackagesManager

I updated things to Python 3.8, because there was a bug with https://github.com/lark-parser/lark dependency on startup, then, I updated it to the latest version, which requires python greater than 3.3.

You could clone this repository and remove the `.python-version` file from your copy of this package, or install my fork of package control.
